name: Build M348 deployment packages

on:
  workflow_dispatch:
jobs:
  build-deps:
    uses: ./.github/workflows/deploy-cran-repo.yml
    with:
      packages: |
        zoo
        xts
        TTR
        lattice
        jsonlite
        Rcpp
        digest
        generics
        Formula
        bdsmatrix
        sandwich
        urca
        miscTools
        maxLik
        nlme
        MASS
        rbibutils
        Rdpack
        formatR
      webr-image: "ghcr.io/r-wasm/webr:v0.3.3"
      compress: false

  build-main:
    needs: build-deps
    uses: ./.github/workflows/deploy-cran-repo.yml
    with:
      packages: |
        local::./packages/JupyterLiteUtils_0.0.1.tar.gz
        local::./packages/M348_1.3.6.4.tar.gz
        local::./packages/MASS_7.3-58.3.tar.gz
        lmtest
        local::./packages/quantmod_0.4.26.1.tar.gz
        collapse
        plm
      webr-image: "ghcr.io/r-wasm/webr:v0.3.3"
      compress: false
