name: Build and Deploy

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: r-wasm/actions/.github/workflows/deploy-cran-repo.yml@v2
      with:
        packages: local::./packages/M348_1.3.4.tar.gz
        webr-image: "ghcr.io/r-wasm/webr:main"  # Optional: use the default or specify a different one
        compress: true  # Optional: compress Emscripten VFS images if needed