name: Build M348 deployment packages

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/deploy-cran-repo.yml
    with:
      packages: |
        local::./packages/M348_1.3.4.tar.gz
        lattice
        MASS
        nlme
        urca
        lmtest
        zoo
        plm
        formatR
      webr-image: "ghcr.io/r-wasm/webr:v0.3.3"
      compress: false
