name: Build M348 deployment packages

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/deploy-cran-repo.yml
    with:
      packages: |
        local::./packages/M348_1.3.4.tar.gz
        local::./packages/tseries_0.10-54.tar.gz
        local::./packages/MASS_7.3-58.3.tar.gz
        lattice
        nlme
        urca
        lmtest
        zoo
        jsonlite
        xts
        TTR
        local::./packages/curl_5.0.1.tar.gz
        local::./packages/quantmod_0.4.26.1.tgz
        plm
        formatR
        Formula
        bdsmatrix
        sandwich
        Rcpp
        collapse
        generics
        maxLik
        quadprog
        digest
        miscTools
        rbibutils
        Rdpack
      webr-image: "ghcr.io/r-wasm/webr:v0.3.3"
      compress: false
