name: Build M348 test package

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/deploy-cran-repo.yml
    with:
      packages: local::./packages/M348_1.3.4.tar.gz
      webr-image: "ghcr.io/r-wasm/webr:main"
      compress: true