name: Build M348 deployment packages
on:
  workflow_dispatch:
    inputs:
      webr-image:
        description: 'Select WebR image version'
        required: true
        default: 'ghcr.io/r-wasm/webr:v0.4.4'
        type: choice
        options:
          - 'ghcr.io/r-wasm/webr:v0.3.3'
          - 'ghcr.io/r-wasm/webr:v0.4.4'
          - 'ghcr.io/r-wasm/webr:v0.5.4'
          - 'ghcr.io/r-wasm/webr:v0.5.5'
      compress:
        description: 'Enable compression'
        required: true
        default: true
        type: boolean

jobs:
  build:
    uses: r-wasm/actions/.github/workflows/deploy-cran-repo.yml@v2
    with:
      packages: |
        local::./packages/JupyterLiteUtils_0.0.1.tar.gz
        local::./packages/M348_1.3.7.tar.gz
        local::./packages/MASS_7.3-58.3.tar.gz
        lattice
        nlme
        urca
        zoo
        lmtest
        local::./packages/quantmod_0.4.26.1.tar.gz
        jsonlite
        xts
        TTR
        Rcpp
        collapse
        formatR
        Formula
        bdsmatrix
        sandwich
        generics
        digest
        miscTools
        maxLik
        rbibutils
        Rdpack
        plm
      webr-image: ${{ inputs.webr-image }}
      compress: ${{ inputs.compress }}
    permissions:
      # To download GitHub Packages within action
      repository-projects: read
      # For publishing to pages environment
      pages: write
      id-token: write
